/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/cyberpunk_desk/scene.gltf -t -r public 
Author: Cisco (https://sketchfab.com/Ciscow)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cyberpunk-desk-8bc4ca48b2e244ff8b5ba714a2ec1963
Title: Cyberpunk Desk
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh
    Object_3: THREE.Mesh
    Object_4: THREE.Mesh
    Object_5: THREE.Mesh
    Object_6: THREE.Mesh
    Object_7: THREE.Mesh
    Object_8: THREE.Mesh
  }
  materials: {
    ['1041']: THREE.MeshStandardMaterial
    ['1042']: THREE.MeshStandardMaterial
    ['1043']: THREE.MeshStandardMaterial
    ['1053']: THREE.MeshStandardMaterial
    ['1054']: THREE.MeshStandardMaterial
    ['1055']: THREE.MeshStandardMaterial
    ['1045']: THREE.MeshStandardMaterial
  }
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Desk(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/cyberpunk_desk/scene.gltf') as GLTFResult
  const position: [number, number, number] = [11, -5.5, 8];
  const rotation: [number, number, number] = [-Math.PI / 2, 0, 0];
  const scale = 1.5;

  return (
    <group {...props} position={position} rotation={rotation} scale={scale} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials['1041']} />
      <mesh geometry={nodes.Object_3.geometry} material={materials['1042']} />
      <mesh geometry={nodes.Object_4.geometry} material={materials['1043']} />
      <mesh geometry={nodes.Object_5.geometry} material={materials['1053']} />
      <mesh geometry={nodes.Object_6.geometry} material={materials['1054']} />
      <mesh geometry={nodes.Object_7.geometry} material={materials['1055']} />
      <mesh geometry={nodes.Object_8.geometry} material={materials['1045']} />
    </group>
  )
}

useGLTF.preload('/cyberpunk_desk/scene.gltf')
