/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/spaceShip/spaceShip.gltf -t -r public 
Author: TuppsM (https://sketchfab.com/TuppsM)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/futuristic-racing-car-molnia-738a78a4c9154614b90029bf8bb80d61
Title: Futuristic racing car - "Molnia"
*/


import * as THREE from 'three'
import React, { useRef, forwardRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GroupProps } from '@react-three/fiber'
import { GLTF } from 'three-stdlib'
import { Group } from 'three';

type GLTFResult = GLTF & {
  nodes: {
    Body_Molnia_0: THREE.Mesh
    Cables_Molnia_0: THREE.Mesh
    CablesCover_Molnia_0: THREE.Mesh
    PetalsConnectors_Molnia_0: THREE.Mesh
    Windshield_Molnia_0: THREE.Mesh
    Petal5_Molnia_0: THREE.Mesh
    Petal3_Molnia_0: THREE.Mesh
    Petal7_Molnia_0: THREE.Mesh
    Petal2_Molnia_0: THREE.Mesh
    Petal6_Molnia_0: THREE.Mesh
    Petal4_Molnia_0: THREE.Mesh
    Petal8_Molnia_0: THREE.Mesh
    Petal1_Molnia_0: THREE.Mesh
    _rootJoint: THREE.Bone
  }
  materials: {
    Molnia: THREE.MeshPhysicalMaterial
  }
}


type SpaceShipProps = JSX.IntrinsicElements['group'] & {
  // Aquí puedes añadir cualquier otra prop personalizada si es necesario
};


export const SpaceShip = forwardRef<Group, SpaceShipProps>((props, ref) => {
  const { nodes, materials, animations } = useGLTF('/public/spaceShip/spaceShip.gltf') as GLTFResult
  const position: [number, number, number] = [0, 0, 0];
  const rotation: [number, number, number] = [Math.PI / 2, Math.PI, Math.PI / 2];
  const scale = 0.2;
  return (
    <group ref={ref} {...props} position={position} rotation={rotation} scale={scale} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" position={[0, 0, 0]} rotation={rotation} scale={0.017}>
          <group name="b1b800c422974b2e90ea53dd6ba71b49fbx" rotation={[0, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="MolniaRig" rotation={[0, 0, 0]} scale={100}>
                  <group name="Object_5">
                    <primitive object={nodes._rootJoint} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
});

useGLTF.preload('/public/spaceShip/spaceShip.gltf')
